# Generated by Django 6.1.1 on 2026-09-08 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, default='Welcome to our restaurant!', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('primary_color', models.CharField(default='#FF6B35', max_length=7)),
                ('secondary_color', models.CharField(default='#004E89', max_length=7)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('service_charge_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_prep_time', models.IntegerField(default=20)),
                ('razorpay_key_id', models.CharField(blank=True, default='', max_length=100)),
                ('razorpay_key_secret', models.CharField(blank=True, default='', max_length=100)),
                ('whatsapp_api_token', models.CharField(blank=True, default='', max_length=500)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, default='', max_length=50)),
                ('plan', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='trial', max_length=20)),
                ('plan_expiry', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('kitchen', 'Kitchen Staff'), ('waiter', 'Waiter')], max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'unique_together': {('tenant', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['table_number'],
                'unique_together': {('tenant', 'table_number')},
            },
        ),
    ]
