# Generated by Django 6.1.1 on 2026-09-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Menu page background photo', null=True, upload_to='tenants/backgrounds/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Top banner image', null=True, upload_to='tenants/banners/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Browser tab icon', null=True, upload_to='tenants/favicons/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='footer_text',
            field=models.CharField(blank=True, default='Thank you for dining with us!', help_text='Footer message', max_length=500),
        ),
        migrations.AddField(
            model_name='tenant',
            name='welcome_message',
            field=models.CharField(blank=True, default='Welcome! Scan menu and order.', help_text='Welcome screen message', max_length=300),
        ),
    ]
