# Generated by Django 6.1.1 on 2026-09-09 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('tenants', '0002_tenant_background_image_tenant_banner_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='accepts_reservations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='assigned_waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tables', to='tenants.staff'),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='pos_x',
            field=models.IntegerField(default=0, help_text='X position on floor plan'),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='pos_y',
            field=models.IntegerField(default=0, help_text='Y position on floor plan'),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='table_shape',
            field=models.CharField(choices=[('round', 'Round'), ('square', 'Square'), ('rectangle', 'Rectangle')], default='round', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='reservation_advance',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Advance amount for table reservation', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/banners/'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/favicons/'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='footer_text',
            field=models.CharField(blank=True, default='Thank you for dining with us!', max_length=500),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='welcome_message',
            field=models.CharField(blank=True, default='Welcome! Scan menu and order.', max_length=300),
        ),
        migrations.CreateModel(
            name='ComplimentaryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='Monetary value of service', max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order to get this free', max_digits=10)),
                ('max_per_customer', models.PositiveIntegerField(default=1)),
                ('applicable_days', models.JSONField(blank=True, default=list, help_text='Day numbers (0=Sunday) or empty for all')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complimentary_services', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Complimentary Service',
                'verbose_name_plural': 'Complimentary Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TableLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Floor', max_length=100)),
                ('width', models.PositiveIntegerField(default=800, help_text='Canvas width in pixels')),
                ('height', models.PositiveIntegerField(default=600, help_text='Canvas height in pixels')),
                ('background_color', models.CharField(default='#f5f5f5', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layout', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Table Layout',
                'verbose_name_plural': 'Table Layouts',
            },
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('reservation_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('party_size', models.PositiveIntegerField(default=2)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_payment_method', models.CharField(blank=True, default='', max_length=20)),
                ('advance_payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('advance_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tenants.restauranttable')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Table Reservation',
                'verbose_name_plural': 'Table Reservations',
                'ordering': ['-reservation_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('razorpay', 'Online')], max_length=20)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('customer_name', models.CharField(blank=True, default='', max_length=100)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_payments', to='orders.order')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_advances', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='tenants.tenant')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_payments', to='tenants.tablereservation')),
            ],
            options={
                'verbose_name': 'Advance Payment',
                'verbose_name_plural': 'Advance Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
