# Generated by Django 6.1.1 on 2026-09-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_restauranttable_accepts_reservations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='employee_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='staff/id_proof/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/photos/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='staff/resume/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('kitchen', 'Kitchen Staff'), ('waiter', 'Waiter'), ('cashier', 'Cashier')], max_length=20),
        ),
    ]
