# Generated by Django 6.1.1 on 2026-09-09 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_staff_address_staff_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='fas fa-cog', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('icon', models.CharField(default='fas fa-star', max_length=50)),
                ('price_type', models.CharField(choices=[('free', 'Free'), ('one_time', 'One-Time'), ('monthly', 'Monthly'), ('per_order', 'Per Order')], default='free', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, default=0, help_text='Original price for showing discount', max_digits=10)),
                ('features', models.JSONField(default=list, help_text='JSON list of features')),
                ('manual_title', models.CharField(blank=True, max_length=200)),
                ('manual_content', models.TextField(blank=True, help_text='How to use this service')),
                ('setup_guide_url', models.URLField(blank=True, help_text='Video tutorial URL')),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_beta', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('requires_whatsapp', models.BooleanField(default=False)),
                ('requires_razorpay', models.BooleanField(default=False)),
                ('requires_staff', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory')),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TenantService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Setup'), ('expired', 'Expired')], default='active', max_length=20)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_services', to='services.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_services', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-activated_at'],
                'unique_together': {('tenant', 'service')},
            },
        ),
        migrations.CreateModel(
            name='ServiceUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='services.tenantservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
