# Generated by Django 6.1.1 on 2026-09-13 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('tenants', '0004_staff_address_staff_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('campaign_type', models.CharField(choices=[('promo', 'Promotion'), ('event', 'Event'), ('feedback', 'Feedback'), ('loyalty', 'Loyalty')], max_length=20)),
                ('message', models.TextField()),
                ('send_to_all', models.BooleanField(default=False)),
                ('send_to_inactive', models.BooleanField(default=False)),
                ('send_to_vip', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_delivered', models.IntegerField(default=0)),
                ('total_read', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_campaigns', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(blank=True, max_length=100)),
                ('access_token', models.TextField(blank=True)),
                ('business_account_id', models.CharField(blank=True, max_length=100)),
                ('verify_token', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('auto_send_bill', models.BooleanField(default=True)),
                ('auto_send_reminder', models.BooleanField(default=True)),
                ('reminder_interval_hours', models.IntegerField(default=2)),
                ('bill_message', models.TextField(default='Hi {customer_name}! 🧾\n\nYour bill at {restaurant_name}:\n\n{bill_items}\n\nTotal: ₹{total}\n\nThank you for dining with us! 🙏\n\n- {restaurant_name}')),
                ('payment_reminder', models.TextField(default='Hi {customer_name}! 💰\n\nFriendly reminder: Your bill of ₹{total} at {restaurant_name} is pending.\n\nPlease complete the payment at your convenience.\n\nThank you! 🙏')),
                ('order_confirmation', models.TextField(default="Hi {customer_name}! ✅\n\nYour order #{order_id} has been received!\n\nItems:\n{order_items}\n\nEstimated time: {prep_time} mins\n\nWe'll notify you when it's ready! 🍽️")),
                ('order_ready', models.TextField(default='Hi {customer_name}! 🎉\n\nYour order #{order_id} is READY!\n\nPlease collect from the counter.\n\nEnjoy your meal! 😋')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('bill', 'Bill'), ('payment_reminder', 'Payment Reminder'), ('order_confirmation', 'Order Confirmation'), ('order_ready', 'Order Ready'), ('marketing', 'Marketing'), ('custom', 'Custom')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('message_content', models.TextField()),
                ('message_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
